### Variables
@baseUrl = https://localhost:7205
@apiVersion = 1
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiIwZTZkMWY1MC02MWNkLTQyZjctYWFjOS1lMzkwMmRhYTI3ZmEiLCJzdWIiOiJhZG1pbkBieXRlc2l6ZWJyZXdzLmNvbSIsImVtYWlsIjoiYWRtaW5AYnl0ZXNpemVicmV3cy5jb20iLCJ1c2VyaWQiOiIxZjQ4MjBiMS0yMWE2LTRmZTQtOGRhZC1iODg2ZmFiOTBmOGIiLCJhZG1pbiI6ZmFsc2UsIm5iZiI6MTc1NjA5MjEyOSwiZXhwIjoxNzU2MDkzMDI5LCJpYXQiOjE3NTYwOTIxMjksImlzcyI6Imh0dHBzOi8vaWQuYnl0ZXNpemVicmV3cy5jb20iLCJhdWQiOiJodHRwczovL2F1ZGllbmNlLmJ5dGVzaXplYnJld3MuY29tIn0.nXQRGrP7UriPCx_fp4en3TdqZ551sw3OTBoXl_y1AvQ

### Get All Plants
GET {{baseUrl}}/v{{apiVersion}}/Plants
Accept: application/json
Authorization: Bearer {{token}}
###

### Get Plant By Id
@plantId = 1f4820b1-21a6-4fe4-8dad-b886fab90f8b
GET {{baseUrl}}/v{{apiVersion}}/Plants/{{plantId}}
Accept: application/json
Authorization: Bearer {{token}}

###

### Create Plant
PUT {{baseUrl}}/v{{apiVersion}}/Plants
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "commonName": "Fiddle Leaf Fig",
  "scientificName": "Ficus carica",
  "duration": "Perennial",
  "age": 1,
  "url": "https://plants.usda.gov/plant-profile/FICA"
}

###

### Update Plant By Id
@updatePlantId = 1f4820b1-21a6-4fe4-8dad-b886fab90f8b
PATCH {{baseUrl}}/v{{apiVersion}}/Plants/{{updatePlantId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "duration": "Annual",
  "age": 3,
}

###

### Delete Plant By Id
@deletePlantId = 1f4820b1-21a6-4fe4-8dad-b886fab90f8b
DELETE {{baseUrl}}/v{{apiVersion}}/Plants/{{deletePlantId}}
Authorization: Bearer {{token}}

###